[tool.black]
line-length = 125

[tool.ruff]
line-length = 125
select = ["E", "F", "W", "SIM"]
ignore = ["W292","W293"]
exclude = ["structure.py", "todo.py", "constants.py", "archive"]

[tool.isort]
profile = "black"
line_length = 125